//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDBMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuotteetMyynti10Parasta_kaikkinaAikoina
    {
        public long rowid { get; set; }
        public string Nimi { get; set; }
        public Nullable<decimal> TuotteidenMyynti { get; set; }
    }
}
